// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VISIONSAMPLE_BOW_DATA_H_
#define FLATBUFFERS_GENERATED_VISIONSAMPLE_BOW_DATA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

namespace bow {
namespace data {

struct Vector3;
struct Vector3Builder;

struct Transform;
struct TransformBuilder;

struct ImageSample;
struct ImageSampleBuilder;

struct ImageSamples;
struct ImageSamplesBuilder;

enum CompressionFormat : int8_t {
  CompressionFormat_H264 = 0,
  CompressionFormat_VP8 = 1,
  CompressionFormat_VP9 = 2,
  CompressionFormat_JPG = 3,
  CompressionFormat_RAW = 4,
  CompressionFormat_H265 = 5,
  CompressionFormat_MIN = CompressionFormat_H264,
  CompressionFormat_MAX = CompressionFormat_H265
};

inline const CompressionFormat (&EnumValuesCompressionFormat())[6] {
  static const CompressionFormat values[] = {
    CompressionFormat_H264,
    CompressionFormat_VP8,
    CompressionFormat_VP9,
    CompressionFormat_JPG,
    CompressionFormat_RAW,
    CompressionFormat_H265
  };
  return values;
}

inline const char * const *EnumNamesCompressionFormat() {
  static const char * const names[7] = {
    "H264",
    "VP8",
    "VP9",
    "JPG",
    "RAW",
    "H265",
    nullptr
  };
  return names;
}

inline const char *EnumNameCompressionFormat(CompressionFormat e) {
  if (flatbuffers::IsOutRange(e, CompressionFormat_H264, CompressionFormat_H265)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCompressionFormat()[index];
}

enum ImageType : int8_t {
  ImageType_RGB = 0,
  ImageType_DEPTH = 1,
  ImageType_STEREO = 2,
  ImageType_INFRARED = 3,
  ImageType_MIN = ImageType_RGB,
  ImageType_MAX = ImageType_INFRARED
};

inline const ImageType (&EnumValuesImageType())[4] {
  static const ImageType values[] = {
    ImageType_RGB,
    ImageType_DEPTH,
    ImageType_STEREO,
    ImageType_INFRARED
  };
  return values;
}

inline const char * const *EnumNamesImageType() {
  static const char * const names[5] = {
    "RGB",
    "DEPTH",
    "STEREO",
    "INFRARED",
    nullptr
  };
  return names;
}

inline const char *EnumNameImageType(ImageType e) {
  if (flatbuffers::IsOutRange(e, ImageType_RGB, ImageType_INFRARED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesImageType()[index];
}

enum StereoDesignation : int8_t {
  StereoDesignation_NONE = 0,
  StereoDesignation_LEFT = 1,
  StereoDesignation_RIGHT = 2,
  StereoDesignation_MIN = StereoDesignation_NONE,
  StereoDesignation_MAX = StereoDesignation_RIGHT
};

inline const StereoDesignation (&EnumValuesStereoDesignation())[3] {
  static const StereoDesignation values[] = {
    StereoDesignation_NONE,
    StereoDesignation_LEFT,
    StereoDesignation_RIGHT
  };
  return values;
}

inline const char * const *EnumNamesStereoDesignation() {
  static const char * const names[4] = {
    "NONE",
    "LEFT",
    "RIGHT",
    nullptr
  };
  return names;
}

inline const char *EnumNameStereoDesignation(StereoDesignation e) {
  if (flatbuffers::IsOutRange(e, StereoDesignation_NONE, StereoDesignation_RIGHT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStereoDesignation()[index];
}

enum MediaPipeline : int8_t {
  MediaPipeline_UNKNOWN = 0,
  MediaPipeline_GSTREAMER = 1,
  MediaPipeline_FFMPEG = 2,
  MediaPipeline_OTHER = 3,
  MediaPipeline_MIN = MediaPipeline_UNKNOWN,
  MediaPipeline_MAX = MediaPipeline_OTHER
};

inline const MediaPipeline (&EnumValuesMediaPipeline())[4] {
  static const MediaPipeline values[] = {
    MediaPipeline_UNKNOWN,
    MediaPipeline_GSTREAMER,
    MediaPipeline_FFMPEG,
    MediaPipeline_OTHER
  };
  return values;
}

inline const char * const *EnumNamesMediaPipeline() {
  static const char * const names[5] = {
    "UNKNOWN",
    "GSTREAMER",
    "FFMPEG",
    "OTHER",
    nullptr
  };
  return names;
}

inline const char *EnumNameMediaPipeline(MediaPipeline e) {
  if (flatbuffers::IsOutRange(e, MediaPipeline_UNKNOWN, MediaPipeline_OTHER)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMediaPipeline()[index];
}

enum DepthRepresentation : int8_t {
  DepthRepresentation_UNSPECIFIED = 0,
  DepthRepresentation_RAW_Z16 = 1,
  DepthRepresentation_COLORIZED_RGB = 2,
  DepthRepresentation_MIN = DepthRepresentation_UNSPECIFIED,
  DepthRepresentation_MAX = DepthRepresentation_COLORIZED_RGB
};

inline const DepthRepresentation (&EnumValuesDepthRepresentation())[3] {
  static const DepthRepresentation values[] = {
    DepthRepresentation_UNSPECIFIED,
    DepthRepresentation_RAW_Z16,
    DepthRepresentation_COLORIZED_RGB
  };
  return values;
}

inline const char * const *EnumNamesDepthRepresentation() {
  static const char * const names[4] = {
    "UNSPECIFIED",
    "RAW_Z16",
    "COLORIZED_RGB",
    nullptr
  };
  return names;
}

inline const char *EnumNameDepthRepresentation(DepthRepresentation e) {
  if (flatbuffers::IsOutRange(e, DepthRepresentation_UNSPECIFIED, DepthRepresentation_COLORIZED_RGB)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDepthRepresentation()[index];
}

enum DepthColorization : int8_t {
  DepthColorization_NONE = 0,
  DepthColorization_HUE_LINEAR_Z16 = 1,
  DepthColorization_HUE_INVERSE_DISPARITY = 2,
  DepthColorization_LUMA_LINEAR_Z16 = 3,
  DepthColorization_MIN = DepthColorization_NONE,
  DepthColorization_MAX = DepthColorization_LUMA_LINEAR_Z16
};

inline const DepthColorization (&EnumValuesDepthColorization())[4] {
  static const DepthColorization values[] = {
    DepthColorization_NONE,
    DepthColorization_HUE_LINEAR_Z16,
    DepthColorization_HUE_INVERSE_DISPARITY,
    DepthColorization_LUMA_LINEAR_Z16
  };
  return values;
}

inline const char * const *EnumNamesDepthColorization() {
  static const char * const names[5] = {
    "NONE",
    "HUE_LINEAR_Z16",
    "HUE_INVERSE_DISPARITY",
    "LUMA_LINEAR_Z16",
    nullptr
  };
  return names;
}

inline const char *EnumNameDepthColorization(DepthColorization e) {
  if (flatbuffers::IsOutRange(e, DepthColorization_NONE, DepthColorization_LUMA_LINEAR_Z16)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDepthColorization()[index];
}

struct Vector3 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef Vector3Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
};

struct Vector3Builder {
  typedef Vector3 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vector3::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vector3::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vector3::VT_Z, z, 0.0f);
  }
  explicit Vector3Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Vector3> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Vector3>(end);
    return o;
  }
};

inline flatbuffers::Offset<Vector3> CreateVector3(
    flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vector3Builder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct Transform FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TransformBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_EULER_ANGLES = 6,
    VT_LINK_NAME = 8,
    VT_PART = 10
  };
  const bow::data::Vector3 *position() const {
    return GetPointer<const bow::data::Vector3 *>(VT_POSITION);
  }
  const bow::data::Vector3 *euler_angles() const {
    return GetPointer<const bow::data::Vector3 *>(VT_EULER_ANGLES);
  }
  const flatbuffers::String *link_name() const {
    return GetPointer<const flatbuffers::String *>(VT_LINK_NAME);
  }
  const flatbuffers::String *part() const {
    return GetPointer<const flatbuffers::String *>(VT_PART);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyOffset(verifier, VT_EULER_ANGLES) &&
           verifier.VerifyTable(euler_angles()) &&
           VerifyOffset(verifier, VT_LINK_NAME) &&
           verifier.VerifyString(link_name()) &&
           VerifyOffset(verifier, VT_PART) &&
           verifier.VerifyString(part()) &&
           verifier.EndTable();
  }
};

struct TransformBuilder {
  typedef Transform Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_position(flatbuffers::Offset<bow::data::Vector3> position) {
    fbb_.AddOffset(Transform::VT_POSITION, position);
  }
  void add_euler_angles(flatbuffers::Offset<bow::data::Vector3> euler_angles) {
    fbb_.AddOffset(Transform::VT_EULER_ANGLES, euler_angles);
  }
  void add_link_name(flatbuffers::Offset<flatbuffers::String> link_name) {
    fbb_.AddOffset(Transform::VT_LINK_NAME, link_name);
  }
  void add_part(flatbuffers::Offset<flatbuffers::String> part) {
    fbb_.AddOffset(Transform::VT_PART, part);
  }
  explicit TransformBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Transform> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Transform>(end);
    return o;
  }
};

inline flatbuffers::Offset<Transform> CreateTransform(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<bow::data::Vector3> position = 0,
    flatbuffers::Offset<bow::data::Vector3> euler_angles = 0,
    flatbuffers::Offset<flatbuffers::String> link_name = 0,
    flatbuffers::Offset<flatbuffers::String> part = 0) {
  TransformBuilder builder_(_fbb);
  builder_.add_part(part);
  builder_.add_link_name(link_name);
  builder_.add_euler_angles(euler_angles);
  builder_.add_position(position);
  return builder_.Finish();
}

inline flatbuffers::Offset<Transform> CreateTransformDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<bow::data::Vector3> position = 0,
    flatbuffers::Offset<bow::data::Vector3> euler_angles = 0,
    const char *link_name = nullptr,
    const char *part = nullptr) {
  auto link_name__ = link_name ? _fbb.CreateString(link_name) : 0;
  auto part__ = part ? _fbb.CreateString(part) : 0;
  return bow::data::CreateTransform(
      _fbb,
      position,
      euler_angles,
      link_name__,
      part__);
}

struct ImageSample FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ImageSampleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOURCE = 4,
    VT_DATA = 6,
    VT_DATA_SHAPE = 8,
    VT_COMPRESSION = 10,
    VT_IMAGE_TYPE = 12,
    VT_TRANSFORM = 14,
    VT_FRAME_NUMBER = 16,
    VT_DESIGNATION = 18,
    VT_HFOV = 20,
    VT_VFOV = 22,
    VT_NEW_DATA_FLAG = 24,
    VT_MIN = 26,
    VT_MAX = 28,
    VT_PIPELINE = 30,
    VT_CODEC_HEADER = 32,
    VT_CAPTURED_UNIX_NS = 34,
    VT_DEPTH_REPRESENTATION = 36,
    VT_DEPTH_COLORIZATION = 38,
    VT_DEPTH_UNIT_METERS = 40
  };
  const flatbuffers::String *source() const {
    return GetPointer<const flatbuffers::String *>(VT_SOURCE);
  }
  const flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  const flatbuffers::Vector<uint32_t> *data_shape() const {
    return GetPointer<const flatbuffers::Vector<uint32_t> *>(VT_DATA_SHAPE);
  }
  bow::data::CompressionFormat compression() const {
    return static_cast<bow::data::CompressionFormat>(GetField<int8_t>(VT_COMPRESSION, 3));
  }
  bow::data::ImageType image_type() const {
    return static_cast<bow::data::ImageType>(GetField<int8_t>(VT_IMAGE_TYPE, 0));
  }
  const bow::data::Transform *transform() const {
    return GetPointer<const bow::data::Transform *>(VT_TRANSFORM);
  }
  uint64_t frame_number() const {
    return GetField<uint64_t>(VT_FRAME_NUMBER, 0);
  }
  bow::data::StereoDesignation designation() const {
    return static_cast<bow::data::StereoDesignation>(GetField<int8_t>(VT_DESIGNATION, 0));
  }
  float hfov() const {
    return GetField<float>(VT_HFOV, 0.0f);
  }
  float vfov() const {
    return GetField<float>(VT_VFOV, 0.0f);
  }
  bool new_data_flag() const {
    return GetField<uint8_t>(VT_NEW_DATA_FLAG, 1) != 0;
  }
  uint32_t min() const {
    return GetField<uint32_t>(VT_MIN, 0);
  }
  uint32_t max() const {
    return GetField<uint32_t>(VT_MAX, 0);
  }
  bow::data::MediaPipeline pipeline() const {
    return static_cast<bow::data::MediaPipeline>(GetField<int8_t>(VT_PIPELINE, 0));
  }
  const flatbuffers::Vector<uint8_t> *codec_header() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_CODEC_HEADER);
  }
  uint64_t captured_unix_ns() const {
    return GetField<uint64_t>(VT_CAPTURED_UNIX_NS, 0);
  }
  bow::data::DepthRepresentation depth_representation() const {
    return static_cast<bow::data::DepthRepresentation>(GetField<int8_t>(VT_DEPTH_REPRESENTATION, 0));
  }
  bow::data::DepthColorization depth_colorization() const {
    return static_cast<bow::data::DepthColorization>(GetField<int8_t>(VT_DEPTH_COLORIZATION, 0));
  }
  float depth_unit_meters() const {
    return GetField<float>(VT_DEPTH_UNIT_METERS, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyString(source()) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyOffset(verifier, VT_DATA_SHAPE) &&
           verifier.VerifyVector(data_shape()) &&
           VerifyField<int8_t>(verifier, VT_COMPRESSION, 1) &&
           VerifyField<int8_t>(verifier, VT_IMAGE_TYPE, 1) &&
           VerifyOffset(verifier, VT_TRANSFORM) &&
           verifier.VerifyTable(transform()) &&
           VerifyField<uint64_t>(verifier, VT_FRAME_NUMBER, 8) &&
           VerifyField<int8_t>(verifier, VT_DESIGNATION, 1) &&
           VerifyField<float>(verifier, VT_HFOV, 4) &&
           VerifyField<float>(verifier, VT_VFOV, 4) &&
           VerifyField<uint8_t>(verifier, VT_NEW_DATA_FLAG, 1) &&
           VerifyField<uint32_t>(verifier, VT_MIN, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAX, 4) &&
           VerifyField<int8_t>(verifier, VT_PIPELINE, 1) &&
           VerifyOffset(verifier, VT_CODEC_HEADER) &&
           verifier.VerifyVector(codec_header()) &&
           VerifyField<uint64_t>(verifier, VT_CAPTURED_UNIX_NS, 8) &&
           VerifyField<int8_t>(verifier, VT_DEPTH_REPRESENTATION, 1) &&
           VerifyField<int8_t>(verifier, VT_DEPTH_COLORIZATION, 1) &&
           VerifyField<float>(verifier, VT_DEPTH_UNIT_METERS, 4) &&
           verifier.EndTable();
  }
};

struct ImageSampleBuilder {
  typedef ImageSample Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_source(flatbuffers::Offset<flatbuffers::String> source) {
    fbb_.AddOffset(ImageSample::VT_SOURCE, source);
  }
  void add_data(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(ImageSample::VT_DATA, data);
  }
  void add_data_shape(flatbuffers::Offset<flatbuffers::Vector<uint32_t>> data_shape) {
    fbb_.AddOffset(ImageSample::VT_DATA_SHAPE, data_shape);
  }
  void add_compression(bow::data::CompressionFormat compression) {
    fbb_.AddElement<int8_t>(ImageSample::VT_COMPRESSION, static_cast<int8_t>(compression), 3);
  }
  void add_image_type(bow::data::ImageType image_type) {
    fbb_.AddElement<int8_t>(ImageSample::VT_IMAGE_TYPE, static_cast<int8_t>(image_type), 0);
  }
  void add_transform(flatbuffers::Offset<bow::data::Transform> transform) {
    fbb_.AddOffset(ImageSample::VT_TRANSFORM, transform);
  }
  void add_frame_number(uint64_t frame_number) {
    fbb_.AddElement<uint64_t>(ImageSample::VT_FRAME_NUMBER, frame_number, 0);
  }
  void add_designation(bow::data::StereoDesignation designation) {
    fbb_.AddElement<int8_t>(ImageSample::VT_DESIGNATION, static_cast<int8_t>(designation), 0);
  }
  void add_hfov(float hfov) {
    fbb_.AddElement<float>(ImageSample::VT_HFOV, hfov, 0.0f);
  }
  void add_vfov(float vfov) {
    fbb_.AddElement<float>(ImageSample::VT_VFOV, vfov, 0.0f);
  }
  void add_new_data_flag(bool new_data_flag) {
    fbb_.AddElement<uint8_t>(ImageSample::VT_NEW_DATA_FLAG, static_cast<uint8_t>(new_data_flag), 1);
  }
  void add_min(uint32_t min) {
    fbb_.AddElement<uint32_t>(ImageSample::VT_MIN, min, 0);
  }
  void add_max(uint32_t max) {
    fbb_.AddElement<uint32_t>(ImageSample::VT_MAX, max, 0);
  }
  void add_pipeline(bow::data::MediaPipeline pipeline) {
    fbb_.AddElement<int8_t>(ImageSample::VT_PIPELINE, static_cast<int8_t>(pipeline), 0);
  }
  void add_codec_header(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> codec_header) {
    fbb_.AddOffset(ImageSample::VT_CODEC_HEADER, codec_header);
  }
  void add_captured_unix_ns(uint64_t captured_unix_ns) {
    fbb_.AddElement<uint64_t>(ImageSample::VT_CAPTURED_UNIX_NS, captured_unix_ns, 0);
  }
  void add_depth_representation(bow::data::DepthRepresentation depth_representation) {
    fbb_.AddElement<int8_t>(ImageSample::VT_DEPTH_REPRESENTATION, static_cast<int8_t>(depth_representation), 0);
  }
  void add_depth_colorization(bow::data::DepthColorization depth_colorization) {
    fbb_.AddElement<int8_t>(ImageSample::VT_DEPTH_COLORIZATION, static_cast<int8_t>(depth_colorization), 0);
  }
  void add_depth_unit_meters(float depth_unit_meters) {
    fbb_.AddElement<float>(ImageSample::VT_DEPTH_UNIT_METERS, depth_unit_meters, 0.0f);
  }
  explicit ImageSampleBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ImageSample> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ImageSample>(end);
    return o;
  }
};

inline flatbuffers::Offset<ImageSample> CreateImageSample(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> source = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint32_t>> data_shape = 0,
    bow::data::CompressionFormat compression = bow::data::CompressionFormat_JPG,
    bow::data::ImageType image_type = bow::data::ImageType_RGB,
    flatbuffers::Offset<bow::data::Transform> transform = 0,
    uint64_t frame_number = 0,
    bow::data::StereoDesignation designation = bow::data::StereoDesignation_NONE,
    float hfov = 0.0f,
    float vfov = 0.0f,
    bool new_data_flag = true,
    uint32_t min = 0,
    uint32_t max = 0,
    bow::data::MediaPipeline pipeline = bow::data::MediaPipeline_UNKNOWN,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> codec_header = 0,
    uint64_t captured_unix_ns = 0,
    bow::data::DepthRepresentation depth_representation = bow::data::DepthRepresentation_UNSPECIFIED,
    bow::data::DepthColorization depth_colorization = bow::data::DepthColorization_NONE,
    float depth_unit_meters = 0.0f) {
  ImageSampleBuilder builder_(_fbb);
  builder_.add_captured_unix_ns(captured_unix_ns);
  builder_.add_frame_number(frame_number);
  builder_.add_depth_unit_meters(depth_unit_meters);
  builder_.add_codec_header(codec_header);
  builder_.add_max(max);
  builder_.add_min(min);
  builder_.add_vfov(vfov);
  builder_.add_hfov(hfov);
  builder_.add_transform(transform);
  builder_.add_data_shape(data_shape);
  builder_.add_data(data);
  builder_.add_source(source);
  builder_.add_depth_colorization(depth_colorization);
  builder_.add_depth_representation(depth_representation);
  builder_.add_pipeline(pipeline);
  builder_.add_new_data_flag(new_data_flag);
  builder_.add_designation(designation);
  builder_.add_image_type(image_type);
  builder_.add_compression(compression);
  return builder_.Finish();
}

inline flatbuffers::Offset<ImageSample> CreateImageSampleDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *source = nullptr,
    const std::vector<uint8_t> *data = nullptr,
    const std::vector<uint32_t> *data_shape = nullptr,
    bow::data::CompressionFormat compression = bow::data::CompressionFormat_JPG,
    bow::data::ImageType image_type = bow::data::ImageType_RGB,
    flatbuffers::Offset<bow::data::Transform> transform = 0,
    uint64_t frame_number = 0,
    bow::data::StereoDesignation designation = bow::data::StereoDesignation_NONE,
    float hfov = 0.0f,
    float vfov = 0.0f,
    bool new_data_flag = true,
    uint32_t min = 0,
    uint32_t max = 0,
    bow::data::MediaPipeline pipeline = bow::data::MediaPipeline_UNKNOWN,
    const std::vector<uint8_t> *codec_header = nullptr,
    uint64_t captured_unix_ns = 0,
    bow::data::DepthRepresentation depth_representation = bow::data::DepthRepresentation_UNSPECIFIED,
    bow::data::DepthColorization depth_colorization = bow::data::DepthColorization_NONE,
    float depth_unit_meters = 0.0f) {
  auto source__ = source ? _fbb.CreateString(source) : 0;
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  auto data_shape__ = data_shape ? _fbb.CreateVector<uint32_t>(*data_shape) : 0;
  auto codec_header__ = codec_header ? _fbb.CreateVector<uint8_t>(*codec_header) : 0;
  return bow::data::CreateImageSample(
      _fbb,
      source__,
      data__,
      data_shape__,
      compression,
      image_type,
      transform,
      frame_number,
      designation,
      hfov,
      vfov,
      new_data_flag,
      min,
      max,
      pipeline,
      codec_header__,
      captured_unix_ns,
      depth_representation,
      depth_colorization,
      depth_unit_meters);
}

struct ImageSamples FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ImageSamplesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SAMPLES = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<bow::data::ImageSample>> *samples() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<bow::data::ImageSample>> *>(VT_SAMPLES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SAMPLES) &&
           verifier.VerifyVector(samples()) &&
           verifier.VerifyVectorOfTables(samples()) &&
           verifier.EndTable();
  }
};

struct ImageSamplesBuilder {
  typedef ImageSamples Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_samples(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<bow::data::ImageSample>>> samples) {
    fbb_.AddOffset(ImageSamples::VT_SAMPLES, samples);
  }
  explicit ImageSamplesBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ImageSamples> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ImageSamples>(end);
    return o;
  }
};

inline flatbuffers::Offset<ImageSamples> CreateImageSamples(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<bow::data::ImageSample>>> samples = 0) {
  ImageSamplesBuilder builder_(_fbb);
  builder_.add_samples(samples);
  return builder_.Finish();
}

inline flatbuffers::Offset<ImageSamples> CreateImageSamplesDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<bow::data::ImageSample>> *samples = nullptr) {
  auto samples__ = samples ? _fbb.CreateVector<flatbuffers::Offset<bow::data::ImageSample>>(*samples) : 0;
  return bow::data::CreateImageSamples(
      _fbb,
      samples__);
}

inline const bow::data::ImageSample *GetImageSample(const void *buf) {
  return flatbuffers::GetRoot<bow::data::ImageSample>(buf);
}

inline const bow::data::ImageSample *GetSizePrefixedImageSample(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<bow::data::ImageSample>(buf);
}

inline const char *ImageSampleIdentifier() {
  return "VSM1";
}

inline bool ImageSampleBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, ImageSampleIdentifier());
}

inline bool SizePrefixedImageSampleBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, ImageSampleIdentifier(), true);
}

inline bool VerifyImageSampleBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<bow::data::ImageSample>(ImageSampleIdentifier());
}

inline bool VerifySizePrefixedImageSampleBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<bow::data::ImageSample>(ImageSampleIdentifier());
}

inline void FinishImageSampleBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<bow::data::ImageSample> root) {
  fbb.Finish(root, ImageSampleIdentifier());
}

inline void FinishSizePrefixedImageSampleBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<bow::data::ImageSample> root) {
  fbb.FinishSizePrefixed(root, ImageSampleIdentifier());
}

}  // namespace data
}  // namespace bow

#endif  // FLATBUFFERS_GENERATED_VISIONSAMPLE_BOW_DATA_H_
